/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Karlin
 */
public class FrmFigura extends javax.swing.JFrame {

    /**
     * Creates new form Figuras
     */
    public FrmFigura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panal = new javax.swing.JPanel();
        lblladoa = new javax.swing.JLabel();
        lblladob = new javax.swing.JLabel();
        lblladoc = new javax.swing.JLabel();
        lbllargo = new javax.swing.JLabel();
        lblancho = new javax.swing.JLabel();
        txtladob = new javax.swing.JTextField();
        txtladoa = new javax.swing.JTextField();
        txtladoc = new javax.swing.JTextField();
        txtancho = new javax.swing.JTextField();
        txtlargo = new javax.swing.JTextField();
        cmbFigura = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panal.setBackground(new java.awt.Color(153, 153, 255));

        lblladoa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblladoa.setText("Lado A");

        lblladob.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblladob.setText("Lado B");

        lblladoc.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblladoc.setText("Lado C");

        lbllargo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lbllargo.setText("Largo");

        lblancho.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblancho.setText("Ancho");

        cmbFigura.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cmbFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleciona una figura", "Triangulo", "Cuadrado", "Rectangulo" }));

        btnCalcular.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCalcular.setText("Calcular");

        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        javax.swing.GroupLayout panalLayout = new javax.swing.GroupLayout(panal);
        panal.setLayout(panalLayout);
        panalLayout.setHorizontalGroup(
            panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalLayout.createSequentialGroup()
                        .addComponent(lbllargo)
                        .addGap(50, 50, 50)
                        .addComponent(txtlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(lblancho)
                        .addGap(37, 37, 37)
                        .addComponent(txtancho, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panalLayout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(257, 257, 257))))
            .addGroup(panalLayout.createSequentialGroup()
                .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblladoa)
                        .addGap(37, 37, 37)
                        .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panalLayout.createSequentialGroup()
                                .addComponent(txtladoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lblladob)
                                .addGap(35, 35, 35)
                                .addComponent(txtladob, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblladoc)
                                .addGap(35, 35, 35)
                                .addComponent(txtladoc, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panalLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(cmbFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panalLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panalLayout.setVerticalGroup(
            panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cmbFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtladob, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblladob))
                    .addComponent(txtladoa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblladoa)
                    .addComponent(lblladoc)
                    .addComponent(txtladoc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblancho)
                    .addComponent(txtancho, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlargo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JComboBox<String> cmbFigura;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblancho;
    public javax.swing.JLabel lblladoa;
    public javax.swing.JLabel lblladob;
    public javax.swing.JLabel lblladoc;
    public javax.swing.JLabel lbllargo;
    public javax.swing.JPanel panal;
    public javax.swing.JTextArea txtRespuesta;
    public javax.swing.JTextField txtancho;
    public javax.swing.JTextField txtladoa;
    public javax.swing.JTextField txtladob;
    public javax.swing.JTextField txtladoc;
    public javax.swing.JTextField txtlargo;
    // End of variables declaration//GEN-END:variables
}
